{
 "title": "CDR Search",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "search", "label": "Search" }
  ]
 },
 "panels": [
  {
   "title": "Call Histogram",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate({type=\"log\"} |= `CDR` |~ \"$search\" [$__interval])"
    }
   ]
  },
  {
   "title": "Call Search",
   "type": "logs",
   "gridPos": { "h": 17, "w": 17, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "{type=\"log\"} |= `CDR` |~ \"$search\""
    }
   ]
  },
  {
   "title": "Top Cost",
   "type": "piechart",
   "gridPos": { "h": 17, "w": 7, "x": 17, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum_over_time({type=\"log\"} |= `CDR` |~ \"$search\" | logfmt | COST > 0.005 | unwrap COST [$__interval]) by (FROM, TO)"
    }
   ]
  }
 ]
}