{
 "title": "QOS Horaclifix",
 "tags": [ "qos" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Incomming MOS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(horaclifix_rtp_mos{direction=\"inc\"}[1h]) < 5 and changes(horaclifix_rtp_mos{direction=\"inc\"}[1m]) > 0 and horaclifix_rtp_mos{direction=\"inc\"} > 0",
     "legendFormat": "{{inc_realm}} <--> {{out_realm}}"
    }
   ]
  },
  {
   "title": "Outgoing MOS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(horaclifix_rtp_mos{direction=\"out\"}[1h]) < 5 and changes(horaclifix_rtp_mos{direction=\"out\"}[1m]) > 0 and horaclifix_rtp_mos{direction=\"out\"} > 0",
     "legendFormat": "{{inc_realm}} <--> {{out_realm}}"
    }
   ]
  },
  {
   "title": "Incomming Jitter > 20 ms",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(horaclifix_rtp_avg_jitter{direction=\"inc\"}[1h]) > 20 and changes(horaclifix_rtp_avg_jitter{direction=\"inc\"}[1m]) > 0",
     "legendFormat": "{{inc_realm}} <--> {{out_realm}}"
    }
   ]
  },
  {
   "title": "Outgoing Jitter > 20 ms",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(horaclifix_rtp_avg_jitter{direction=\"out\"}[1h]) > 20 and changes(horaclifix_rtp_avg_jitter{direction=\"out\"}[1m]) > 0",
     "legendFormat": "{{inc_realm}} <--> {{out_realm}}"
    }
   ]
  },
  {
   "title": "Incomming Packet Loss > 20",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(horaclifix_rtp_lost_packets{direction=\"inc\"}[1h]) > 20 and changes(horaclifix_rtp_lost_packets{direction=\"inc\"}[1m]) > 0",
     "legendFormat": "{{inc_realm}} <--> {{out_realm}}"
    }
   ]
  },
  {
   "title": "Outgoing Packet Loss > 20",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(horaclifix_rtp_lost_packets{direction=\"out\"}[30m]) > 20 and changes(horaclifix_rtp_lost_packets{direction=\"out\"}[1m]) > 0",
     "legendFormat": "{{inc_realm}} <--> {{out_realm}}"
    }
   ]
  },
  {
   "title": "Incomming Latency > 20 ms",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(horaclifix_rtcp_avg_lat{direction=\"inc\"}[30m]) > 20 and changes(horaclifix_rtcp_avg_lat{direction=\"inc\"}[1m]) > 0",
     "legendFormat": "{{inc_realm}} <--> {{out_realm}}"
    }
   ]
  },
  {
   "title": "Outgoing Latency > 20 ms",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(horaclifix_rtcp_avg_lat{direction=\"out\"}[30m]) > 20 and changes(horaclifix_rtcp_avg_lat{direction=\"out\"}[1m]) > 0",
     "legendFormat": "{{inc_realm}} <--> {{out_realm}}"
    }
   ]
  }
 ]
}