{
 "title": "SIP Overview",
 "tags": [ "sip" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "tn",
    "label": "interface_name",
    "query": "label_values(heplify_method_response, target_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "KPI's",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "clamp_max((sum(increase(heplify_method_response{target_name=~\"$tn\", method=\"INVITE\", response=\"200\"}[15m])) * 100) / \n(sum(increase(heplify_method_response{target_name=~\"$tn\", method=\"INVITE\", response=\"INVITE\"}[15m])) - \n(sum(increase(heplify_method_response{target_name=~\"$tn\", method=\"INVITE\", response=~\"3.*|401|407\"}[15m])) or sum(up) * 0)), 100)",
     "legendFormat": "ASR"
    },
    {
     "expr": "clamp_max((sum(increase(heplify_method_response{target_name=~\"$tn\", method=\"INVITE\", response=~\"200|480|486|600|603\"}[15m])) * 100) / \n(sum(increase(heplify_method_response{target_name=~\"$tn\", method=\"INVITE\", response=\"INVITE\"}[15m])) - \n(sum(increase(heplify_method_response{target_name=~\"$tn\", method=\"INVITE\", response=~\"3.*|401|407\"}[15m])) or sum(up) * 0)), 100)",
     "legendFormat": "NER"
    },
    {
     "expr": "clamp_max(((sum(increase(heplify_method_response{target_name=~\"$tn\", method=\"REGISTER\", response=~\"4.*|5.*|6.*\"}[15m])) - \nsum(increase(heplify_method_response{target_name=~\"$tn\", method=\"REGISTER\", response=~\"401|402|407\"}[15m]))) * 100) / \n(sum(increase(heplify_method_response{target_name=~\"$tn\", method=\"REGISTER\", response=\"REGISTER\"}[15m]))), 100)",
     "legendFormat": "IRA"
    }
   ]
  },
  {
   "title": "Successful Calls & Register per second",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(direction,node_id)(rate(heplify_method_response{target_name=~\"$tn\", method=\"INVITE\", response=\"200\"}[1m]))",
     "legendFormat": "CPS"
    },
    {
     "expr": "sum without(direction,node_id)(rate(heplify_method_response{target_name=~\"$tn\", method=\"REGISTER\", response=\"200\"}[1m]))",
     "legendFormat": "RPS"
    }
   ]
  },
  {
   "title": "Invite & Register 403 | 404 | 408 | 480 | 482",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(direction,node_id)(rate(heplify_method_response{target_name=~\"$tn\", method=~\"INVITE|REGISTER\" ,response=~\"403|404|408|480|482\"}[2m]))",
     "legendFormat": "{{ method }} {{ response }}"
    }
   ]
  },
  {
   "title": "Invite & Register 50.*",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(direction,node_id)(rate(heplify_method_response{target_name=~\"$tn\",method=~\"INVITE|REGISTER\", response=~\"50.*\"}[2m]))",
     "legendFormat": "{{ method }} {{ response }}"
    }
   ]
  }
 ]
}