{
 "title": "SIP Methods & Responses",
 "tags": [ "sip" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "tn",
    "label": "interface_name",
    "query": "label_values(heplify_method_response, target_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "INVITE per second",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum without(direction,node_id) (rate(heplify_method_response{target_name=~\"$tn\", method=\"INVITE\"}[10m]))",
     "legendFormat": "{{ target_name }}: {{ method }} {{ response }}"
    }
   ]
  },
  {
   "title": "REGISTER per second",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum without(direction,node_id) (rate(heplify_method_response{target_name=~\"$tn\", method=\"REGISTER\"}[2m]))",
     "legendFormat": "{{ target_name }}: {{ method }} {{ response }}"
    }
   ]
  },
  {
   "title": "!INVITE & !REGISTER per second",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum without(direction,node_id) (rate(heplify_method_response{target_name=~\"$tn\", method!=\"REGISTER\", method=\"INVITE\"}[10m]))",
     "legendFormat": "{{ target_name }}: {{ method }} {{ response }}"
    }
   ]
  }
 ]
}